### ISSUE TITLE
Redmine 500 error - create a New Issue

### ISSUE THREAD

**Issue by darioajr** [sameersbn/docker-redmine#133]
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.

Tested versions: 3.0.4, 3.1.0 and 2.6.5 (Same error)
Logs: Don´t show nothing.

**Comment by darioajr** [comment]
![500error](https://cloud.githubusercontent.com/assets/7606/8971945/c099f92c-362b-11e5-95a8-eab94d5c068e.PNG)

**Comment by darioajr** [comment]
This container is running on 

CentOS Linux release 7.1.1503 (Core)
3.10.0-229.7.2.el7.x86_64

**Comment by sameersbn** [comment]
@darioajr please make sure that you have loaded the default configuration from the administration page.

**Comment by darioajr** [comment]
Yes, I loaded the default configurations In English and In Portuguese (New container), but the error persists.

**Comment by sameersbn** [comment]
@darioajr ok.. at this point I would suggest turning off selinux and retrying.

**Comment by darioajr** [comment]
SELINUX of host machine was disabled.

**Comment by sameersbn** [comment]
@darioajr ok.. can you share you docker run or docker-compose.yml file so that I can try to reproduce this issue.

**Comment by darioajr** [comment]
redmine:
  image: sameersbn/redmine:3.1.0
  environment:
    - TZ=America/Sao_Paulo
    - REDMINE_PORT=10083
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=mailserv.xxxxxxxx.com.br
    - SMTP_HOST=mailserv.xxxxxxxx.com.br
    - SMTP_PORT=25
    - DB_TYPE=mysql
    - DB_HOST=bnsvher348
    - DB_NAME=redmine
    - DB_USER=redmine
    - DB_PASS=Redmine@2015.
    - NGINX_MAX_UPLOAD_SIZE=999m
  ports:
    - "10083:80"
  volumes:
    - /srv/docker/redmine/:/home/redmine/data

**Comment by darioajr** [comment]
Howto capture the log to this error??

**Comment by sameersbn** [comment]
@darioajr oh.. sorry I did not find the time to look into this. give me a couple if minutes to check.

**Comment by sameersbn** [comment]
@darioajr I checked it and found no issues. can you try the following docker-compose file to check if you see the issue

```yaml
mysql:
  image: sameersbn/mysql:latest
  environment:
    - DB_NAME=redmine
    - DB_USER=redmine
    - DB_PASS=Redmine@2015.
  volumes:
    - /tmp/docker/redmine/postgresql:/var/lib/postgresql
redmine:
  image: sameersbn/redmine:latest
  links:
    - mysql:mysql
  environment:
    - TZ=America/Sao_Paulo
    - REDMINE_PORT=10083
    - DB_TYPE=mysql
    - DB_HOST=mysql
    - DB_NAME=redmine
    - DB_USER=redmine
    - DB_PASS=Redmine@2015.
    - NGINX_MAX_UPLOAD_SIZE=999m
  ports:
    - "10083:80"
  volumes:
    - /tmp/docker/redmine/redmine:/home/redmine/data
```

here is th output of `docker-compose up` http://pastebin.com/77a8fJyj

Remember to load the default configuration first before creating a project. Let me know.

As far as I can tell there is nothing wrong with the image.
