### ISSUE TITLE
Mail setting, ssl: true 

### ISSUE THREAD

**Issue by fzerorubigd** [sameersbn/docker-redmine#149]
I have a working installation of redmine in debian. I want to move to CoreOS and I want to use this build since its the best one! (Thank you)

But the problem is, I want to use yandex.ru emails, and I found that the config for redmine should be like this  : 

```  
email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: smtp.yandex.ru
      port: 465
      ssl: true
      enable_starttls_auto: true
      domain: example.com
      authentication: :login
      user_name: "mail@example.com"
      password: "secret"
```

Also the exact same settings apply to gitlab.you can see the ssl: true and no tls key. 
I check this about 10 time today, and I'm exactly sure that my sample is correct. Is there any way to fix this in my installation?
