### ISSUE TITLE
Letsencrypt

### ISSUE THREAD

**Issue by mc0e** [sameersbn/docker-redmine#197]
I'm seeing a number of the docker based distributions I use add built-in letsencrypt functionality for self configuring ssl.  This is quite useful, and I think it should be considered here.

Philosophically, it'd be nice to encapsulate LetsEncrypt in a separate container, but I'm not sure how the domain authentication would work for that.  Maybe something exists, but so far what I'm seeing is people wrapping the whole thing up within the service container.

**Comment by Slind14** [comment]
+1

**Comment by frank-dspeed** [comment]
i Close this in favor of external nginx container that will allow you to use any nginx container that does ssl termination i am not for adding ssl to Unicorn it self as it is not needed in any setup you will terminate ssl at the frontend facing servers that are not unicorn

**Comment by mc0e** [comment]
Use of SSL is already part of the expected documented use of this container.  This ticket is a request to add key management using LetsEncrypt.

If I was designing this with an expectation of external SSL termination, I'd be trying to remove nginx from the container entirely.  Is that possible?

**Comment by frank-dspeed** [comment]
@mc0e this is possible and already pointed out in the documentation simply use directly the redmine port of the container not the nginx proxy.

**Comment by hwiorn** [comment]
For the record, If someone want to use LetsEncrypt and Redmine only without external nginx(e.g. revers-proxy and subdomain). Actually, I prefer external nginx. But I had to set up Redmine without reverse-proxy. So, You can use configurations like this.

You can use `certbot` image instead of `auto-letsencrypt`. But I do not recommend because it doesn't do auto-renewal. 
```yaml
version: "3.1"

services:
  redmine:
    image: sameersbn/redmine:5.1.1
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - REDMINE_PLUGINS_MIGRATE=true
      - REDMINE_PORT=443
      - REDMINE_HTTPS=true
      - SSL_CERTIFICATE_PATH=/home/redmine/certs/live/example.com/fullchain.pem
      - SSL_KEY_PATH=/home/redmine/certs/live/example.com/privkey.pem
    volumes:
      - ./redmine_certs:/home/redmine/certs
      - ./certbot/data:/home/redmine/redmine/public/.well-known/acme-challenge
  certs-auto-renewal:
    image: gordonchan/auto-letsencrypt
    restart: always
    environment:
      - DOMAINS=example.com
      - EMAIL=admin@example.com
      - CHECK_FREQ=5
    volumes:
      - ./redmine_certs/:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot/.well-known/acme-challenge
```
