### ISSUE TITLE
Add: memcache support

### ISSUE THREAD

**Issue by jcormier** [sameersbn/docker-redmine#236]
After adding sameersb/memcache to docker-compose.yml and adding MEMCACHE_HOST=memcached the unicorn server continuously starts and dies.

As far as I can tell the configuration done in additional_environment.rb isn't correct for rails 4.2 but I don't know ruby or rails so I've no idea how to fix.

I'm using sameersb/redmine:3.3.1

Relevant log from unicorn_stderr.log:

```
/home/redmine/redmine/config/application.rb:80:in `instance_eval': private method `gem' called for #<Rails::Application::Configuration:0x000000043bb740> (NoMethodError)
	from (eval):1:in `<class:Application>'
	from /home/redmine/redmine/config/application.rb:80:in `instance_eval'
	from /home/redmine/redmine/config/application.rb:80:in `<class:Application>'
	from /home/redmine/redmine/config/application.rb:8:in `<module:RedmineApp>'
	from /home/redmine/redmine/config/application.rb:7:in `<top (required)>'
	from /home/redmine/redmine/config/environment.rb:2:in `require'
	from /home/redmine/redmine/config/environment.rb:2:in `<top (required)>'
	from config.ru:4:in `require'
	from config.ru:4:in `block in <main>'
	from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `eval'
	from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `block in builder'
	from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/bin/unicorn_rails:139:in `call'
	from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/bin/unicorn_rails:139:in `block in rails_builder'
	from /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `call'
	from /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `build_app!'
	from /home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:129:in `start'
	from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `<top (required)>'
	from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
	from /home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'
```

**Comment by jcormier** [comment]
@movcale Looking at your posted docker-compose.yml, I noticed you had memcached.  Where you able to get it to work?  When I try I get the crash above.

https://github.com/sameersbn/docker-redmine/issues/231#issuecomment-266025827

**Comment by jcormier** [comment]
Note I had to add MEMCACHE_HOST because I was using docker-compose v2 format which doesn't auto create env variables between linked containers.

Before I made that change i used this command to verify that memcache wasn't getting used.
`docker-compose exec memcached /usr/share/memcached/scripts/memcached-tool 127.0.0.1 stats`

it reported there was zero things being stored in the memcached server.

**Comment by frank-dspeed** [comment]
https://github.com/sameersbn/docker-redmine/issues/225

**Comment by jcormier** [comment]
What does redmine use memcache for?

**Comment by frank-dspeed** [comment]
@jcormier you should really use google for that i think :)

**Comment by jcormier** [comment]
lol I have but surprisingly this github's issues show up prominently in the results.  From the best I can tell it might be usable for the text cache and maybe the session cache.  Not really sure how either of those affects redmine's performance.  The text cache doesn't even require using memcache.

**Comment by frank-dspeed** [comment]
@jcormier ok then i will enlighten you memcache is used in our case for sessions as also Site Caching via NGINX and UNICORN so it stores pre rendered content so that unicorn don't needs to rerender the results.

**Comment by frank-dspeed** [comment]
@jcormier simple massiv example would be hiting F5 (Reload) on a Large Project list would result in a request to unicorn and so would then result in a Database Request that goes back to Unicorn then this get processed and so on for every page reload with memcache this happens only once and memcache returns directly

**Comment by sameersbn** [comment]
> What does redmine use memcache for?

@jcormier I think I've seen memcache hits occurring while accessing the repo browser or when markdown rendering is enabled. I can't remember correctly. But memcached is not extensively used in redmine,

**Comment by sameersbn** [comment]
@jcormier can you try this docker-compose.yml to get redmine with memcached working.
I don't see the unicorn worker dying.

```yaml
version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
    volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql

  memcached:
      image: sameersbn/memcached:latest
      command: -v

  redmine:
    image: sameersbn/redmine:3.4.2
    depends_on:
    - postgresql
    environment:
    - TZ=Asia/Kolkata

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production

    - MEMCACHED_HOST=memcached
    - MEMCACHED_PORT=11211

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=false
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "10083:80"
    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
```
