### ISSUE TITLE
http host will be truncated when redmine redirect.

### ISSUE THREAD

**Issue by laoshancun** [sameersbn/docker-redmine#242]
hi, i got a redmine redirect error.
for example,i visit https://redmine.test.com/ 
```
GET / HTTP/1.1

Host: redmine.test.com

User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3

Accept-Encoding: gzip, deflate, br

Cookie: a=0510100; b=

Connection: keep-alive

Upgrade-Insecure-Requests: 1

If-None-Match: W/"cd0bb657c36a6c82464c7ee1634117ac"

```

and i got response with wrong host
```
HTTP/2.0 302 Found

Server: nginx

Date: Thu, 15 Dec 2016 10:39:15 GMT

Content-Type: text/html; charset=utf-8

Content-Length: 121

Location: https://redmine/login?back_url=https%3A%2F%2Fredmine%2F

X-Frame-Options: SAMEORIGIN

X-XSS-Protection: 1; mode=block

X-Content-Type-Options: nosniff

Cache-Control: no-cache

X-Request-Id: 0f2dc394-84d1-4ff7-a2fa-ee10bbfd2218

X-Runtime: 0.005824

x-accel-buffering: no

Strict-Transport-Security: max-age=0

X-Firefox-Spdy: h2

```
here is my docker-compose.yml
```
mysql-server:
  image: mysql:5.7
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/docker/redmine/mysql/data:/var/lib/mysql
    - /data/docker/redmine/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
  ports:
    - "3306:3306"
  environment:
  #  - .env_db_mysql
    - MYSQL_USER=redmine
    # MYSQL_PASSWORD=zabbix
    - MYSQL_PASSWORD=password
    # MYSQL_ROOT_PASSWORD=
    - MYSQL_ROOT_PASSWORD=password
    # MYSQL_ALLOW_EMPTY_PASSWORD=false
    # MYSQL_DATABASE=zabbix
    - MYSQL_DATABASE=redmine
  user: root
#   networks:
#     zbx_net:
#       aliases:
#        - mysql-server
#        - zabbix-database
#        - mysql-database
redmine:
  user: root
  image: sameersbn/redmine:3.3.0
  environment:
    - REDMINE_HTTPS=true
    - DB_HOST=mysql-server
    - DB_ADAPTER=mysql2
    - DB_NAME=redmine
    - DB_USER=redmine
    - DB_PASS=password
    - TZ=Asia/Shanghai
    - REDMINE_PORT=80
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=163.com
    - SMTP_HOST=smtp.163.com
    - SMTP_PORT=25
    - SMTP_USER=mail@163.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login
    - IMAP_ENABLED=false
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_SSL=true
    - IMAP_INTERVAL=30
  links:
   - mysql-server:mysql-server
  ports:
    - "10083:80"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/docker/redmine/server/data:/home/redmine/data
    - /data/docker/redmine/server/plugins:/home/redmine/redmine/plugins
```
and mysql server log 
```
redmine_mysql-server_1 | 2016-12-15T10:21:17.486385342Z 2016-12-15T10:21:17.486311Z 16 [Note] Aborted connection 16 to db: 'redmine' user: 'redmine' host: '172.18.1.12' (Got an error reading communication packets)
redmine_mysql-server_1 | 2016-12-15T10:21:28.978129474Z 2016-12-15T10:21:28.977986Z 19 [Note] Aborted connection 19 to db: 'redmine' user: 'redmine' host: '172.18.1.12' (Got an error reading communication packets)
redmine_mysql-server_1 | 2016-12-15T10:23:03.897151569Z 2016-12-15T10:23:03.897023Z 21 [Note] Aborted connection 21 to db: 'redmine' user: 'redmine' host: '172.18.1.12' (Got an error reading communication packets)
```
