### ISSUE TITLE
Configuring redmine::database... exited with code 1

### ISSUE THREAD

**Issue by Glideh** [sameersbn/docker-redmine#259]
Fresh install with

```yml
version: '2'

services:
  redmine:
    image: sameersbn/redmine:3.2.5-1
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=redmine
      - DB_PASS="yyyyyyy"
      - DB_NAME=redmine
      - REDMINE_PORT=8080
      - REDMINE_SECRET_TOKEN="zzzzzzzzz"
    ports:
      - "8000:80"
    volumes:
      - ./data:/home/redmine/data
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "xxxxxxx"
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: "yyyyyyy"
    ports:
      - "8006:3306"
```

```
$ docker-compose up -d;docker-compose logs -f redmine
```

> [...]
> redmine_1  | Symlinking dotfiles...
> redmine_1  | Installing configuration templates...
> redmine_1  | Configuring redmine...
> redmine_1  | Configuring redmine::database...........................................................
> redmine_redmine_1 exited with code 1

How can I know what is crashing ?

**Comment by jcormier** [comment]
You could try setting the DEBUG environment variable for the redmine service.

You can also mount the internal log directory.
```
    volumes:
    - ./redmine-data:/home/redmine/data
    - ./redmine-logs:/var/log/redmine
```

**Comment by jcormier** [comment]
https://github.com/sameersbn/docker-redmine/search?utf8=%E2%9C%93&q=DEBUG&type=

**Comment by Glideh** [comment]
```
$ docker-compose exec redmine ls -R /var/log/redmine

/var/log/redmine:
nginx  redmine	supervisor

/var/log/redmine/nginx:

/var/log/redmine/redmine:

/var/log/redmine/supervisor:
```

I can see only 3 empty directories here

**Comment by jcormier** [comment]
Can you provide the whole start log?

**Comment by jcormier** [comment]
The part thats printed to the screen.

**Comment by Glideh** [comment]
You mean this one:

> redmine_1  | Initializing logdir...
> redmine_1  | Initializing datadir...
> redmine_1  | Symlinking dotfiles...
> redmine_1  | Installing configuration templates...
> redmine_1  | Configuring redmine...
> redmine_1  | Configuring redmine::database...........................................................

Each dot after `Configuring redmine::database` seems to be a try with `mysqladmin [...] status`

**Comment by jcormier** [comment]
I was hoping to see the command you ran as well.  When I start my docker-compose, I also see output from the database container as it starts.  This appears to be missing in your included output.

**Comment by Glideh** [comment]
Ok ! The key information was indeed in the db container logs (I was only checking redmine)

> db_1       | 2017-03-28T13:13:51.556588Z 8 [Note] Access denied for user 'redmine'@'172.24.0.3' (using password: YES)

Redmine's container `DB_PASS` environment variable does not seem to take double quotes as variable value delimiter. I replaced:

```yml
services:
  redmine:
    environment:
      - DB_PASS="yyyyyyy"
```

By

```yml
services:
  redmine:
    environment:
      - DB_PASS=yyyyyyy
```

And it worked. Thanks @jcormier
