### ISSUE TITLE
I got an error:  Please specify the database type in use via the DB_TYPE configuration option.

### ISSUE THREAD

**Issue by alstonhuang** [sameersbn/docker-redmine#293]
I got an error : " Please specify the database type in use via the DB_TYPE configuration option."
When I try to use redmine 2.6.9

Here is my yml file
```
version: '2'

services:
  mysql:
    image: sameersbn/mysql:latest
    environment:
    - DB_USER=redmine
    - DB_PASS=sirin_985632
    - DB_NAME=redmine_production
    volumes:
    - /srv/docker/redmine/mysql_08023:/var/lib/mysql
    restart: always

  redmine:
    image: sameersbn/redmine:2.6.9
    depends_on:
    - mysql
    restart: always
    environment:
    - TZ=Asia/Teipei
    - DB_TYPE=mysql2
    - DB_ADAPTER=mysql2
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_USER=redmine
    - DB_PASS=sirin_985632
    - DB_NAME=redmine_production
    - UNICORN_TIMEOUT=600
    - REDMINE_PORT=80
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=/
    - REDMINE_SECRET_TOKEN=asdfhjkOPQWlskdjflksajlfkjafghsdgfjhsguweyiuyxuzxyuixyciuyziuxyczuiyctzyxt
    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=false
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "10083:80"
    volumes:
    - /srv/docker/redmine/redmine_08023:/home/redmine/data
```
But with the same file just modify the tag to 2.6.10 it works.
What 's the problem?
Thanks.
