### ISSUE TITLE
Installing with an existing database

### ISSUE THREAD

**Issue by Glideh** [sameersbn/docker-redmine#312]
I have a db backup and I need to install a new redmine server based on this backup.
I created a db container and injected the data into it, then started a fresh `sameersbn/docker-redmine:3.2.5-1` container attached:

```yml
version: '3'

services:
  redmine:
    image: sameersbn/redmine:3.2.5-1
    depends_on:
      - db
    environment:
      DEBUG: 'true'
      TZ: Europe/Paris
      DB_HOST: db
      DB_USER: redmine
      DB_PASS: "yyyyyy"
      DB_NAME: redmine
      SMTP_USER: zzzzzz@zzzzzz
      SMTP_PASS: "zzzzzz"
      REDMINE_SECRET_TOKEN: "xyzxyzxyz"
    volumes:
      - ./data:/home/redmine/data
      - ./logs:/var/log/redmine
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "xxxxxx"
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: "yyyyyy"
      TZ: "Europe/Paris"
```

Starting the redmine container crashes at migration:

> redmine_1  | + exec_as_redmine bundle exec rake db:migrate
> redmine_1  | ++ whoami
> redmine_1  | + [[ root == redmine ]]
> redmine_1  | + sudo -HEu redmine bundle exec rake db:migrate
> redmine_1  | rake aborted!
> redmine_1  | StandardError: An error has occurred, all later migrations canceled:
> redmine_1  | 
> redmine_1  | Mysql2::Error: Table 'user_preferences' already exists: CREATE TABLE `user_preferences` (`id` int(11) auto_increment PRIMARY KEY, `user_id` int(11) DEFAULT 0 NOT NULL, `others` text) ENGINE=InnoDB
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in '_query'
> 
> [...]
> 
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-12.0.0/exe/rake:27:in '<top (required)>'
> redmine_1  | Tasks: TOP => db:migrate
> redmine_1  | (See full trace by running task with --trace)

It seems to fail because of the existing table, I did that in the past and it applied the migrations well.
Doesn't seem to like it this time, not sure it's related though.

Is it the correct way to start from a db backup ? How can I debug that ?
