### ISSUE TITLE
can't connect database with environment variables

### ISSUE THREAD

**Issue by douhashi** [sameersbn/docker-redmine#338]
my docker-compose.yml below:

```
services:                   
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:                 
      - DB_USER
      - DB_PASS                   
      - DB_NAME
    volumes:                   
      - /srv/docker/redmine/postgresql:/var/lib/postgresql
                           
  redmine:
    image: sameersbn/redmine:3.4.4-2
    depends_on:    
      - postgresql 
    environment: 
      - TZ       
                 
      # FIXME: can't connect db with environment
      - DB_ADAPTER
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME

      ......
```

and export environments below:

```
...
# database settings
export DB_ADAPTER=postgresql
export DB_HOST=postgresql
export DB_PORT=postgresql
export DB_USER=redmine
export DB_PASS=password
export DB_NAME=redmine_production
...
```

then, i got error when docker-compose up

```
redmine_1       | Configuring redmine::database                                                                     
redmine_1       | ERROR:                                                            
redmine_1       |   Please configure the database connection.                                                                             
redmine_1       |   Refer http://git.io/JkE-cw for more information.                                                
redmine_1       |   Cannot continue without a database. Aborting...
redmine_1       |                                         
```

do you have any ideas?
