### ISSUE TITLE
Automatic plugin installation

### ISSUE THREAD

**Issue by iojanis** [sameersbn/docker-redmine#339]
Hello sameersbn,

i'm confused by the praised simplicity that just won't come into effect.
I used my own Dockerfile which inherit your Image and then followed your guide here: 
https://github.com/sameersbn/docker-redmine#installing-plugins

```
mkdir -p /srv/docker/redmine/redmine/plugins
cd /srv/docker/redmine/redmine/plugins
git clone https://github.com/nutso/redmine-plugin-recurring-tasks.git
```

At the moment the image starts, the plugin should be in the specified folder.
But in the administration panel... no plugin will show up.

Have I left something unnoticed?

**Comment by jcormier** [comment]
The plugins folders in redmine have to be named to exactly match what they are registered to in the init.rb file.

https://github.com/nutso/redmine-plugin-recurring-tasks/blob/master/init.rb
```
Redmine::Plugin.register :recurring_tasks do
```

So you need to rename the folder to "recurring_tasks". This is mentioned in the installing section of that github repo.

```
Copy or clone the plugin directory into #{RAILS_ROOT}/plugins/recurring_tasks -- note the folder name 'recurring_tasks' must be verbatim.
```

**Comment by iojanis** [comment]
Thanks for the quick reaction! Unfortunately I haven't got a plugin installed despite your help. This is what my files look like:

Dockerfile
```
FROM sameersbn/redmine:3.4.4-2
RUN cd /srv/docker/redmine/redmine/plugins
RUN git clone https://github.com/nutso/redmine-plugin-recurring-tasks.git
```

docker-compose.yml
```
version: '2'
services:
  db:
    image: mariadb:10.2
    environment:
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=redmineadmin
      - MYSQL_ROOT_PASSWORD=redmineadmin
      - MYSQL_DATABASE=redmine_production
  redmine:
    build: ./DomainSoftware/redmine/.
    ports:
      - "4000:80"
    depends_on:
      - db
    environment:
    - PORT=80
    - TZ=Europe/Berlin
    - DB_PASS=redmineadmin
    - DB_ADAPTER=mysql2
    - DB_HOST=db
    - DB_USER=redmine
    - DB_NAME=redmine_production
    - REDMINE_SECRET_TOKEN=redmineadmin
    - SMTP_ENABLED=false
    - IMAP_ENABLED=false
```
