### ISSUE TITLE
proxy your containers behind apache on docker host

### ISSUE THREAD

**Issue by stefangweichinger** [sameersbn/docker-redmine#370]
Running my https://my.domain.tld on an apache server OK. This is also the docker host where I want to run your images on via this docker-compose.yml:

```
version: '2'

services:
  mariadb:
    image: 'sameersbn/mysql:5.7.22-1'
    environment:
      - DB_USER=redmine
      - DB_PASS=mr-36dfR
      - DB_NAME=redmine_production
    volumes:
      - redmine-db-persistence:/bitnami
  redmine:
    #image: 'bitnami/redmine:latest'
    image: 'sameersbn/redmine:3.4.7-1'
    environment:
      - REDMINE_LANG=de
      - REDMINE_SECRET_TOKEN=adfjvn9
      - REDMINE_HTTPS=true
      - REDMINE_PORT=10083
      - REDMINE_RELATIVE_URL_ROOT=/redmine
      - TZ=Europe/Vienna
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=mr-36dfR
      - DB_NAME=redmine_production

    ports:
      - '8080:10083'
    volumes:
      - redmine-app-persistence:/home/redmine/data
    depends_on:
      - mariadb

volumes:
  redmine-db-persistence:
  redmine-app-persistence:
```

In my /etc/apache2/vhosts.d/00_default_ssl_vhost.conf I have added:

```
<Location /redmine>
    ProxyPass http://127.0.0.1:8080
    ProxyPassReverse http://127.0.0.1:8080
    Require all granted
    </Location>
```

A similar block works fine for my gitea installation, using Port 3000 there, sure.

So far I have no success and wonder if I got the "ports:" right and if that all could work anyway ;-)
pls advise, thanks in advance!

**Comment by stefangweichinger** [comment]
Tried this edited file on my local machine, there this http-URL worked:

```
http://localhost:3001/redmine
```

-> docker-compose.yml:

```
version: '2'

services:
  mariadb:
    image: 'sameersbn/mysql:5.7.22-1'
    environment:
      - DB_USER=redmine
      - DB_PASS=mr-36dfR
      - DB_NAME=redmine_production
    volumes:
      - redmine-db-persistence:/var/lib/mysql
  redmine:
    #image: 'bitnami/redmine:latest'
    image: 'sameersbn/redmine:3.4.7-1'
    environment:
      - REDMINE_LANG=de
      - REDMINE_SECRET_TOKEN=adfjvn9247zkvn
      - REDMINE_RELATIVE_URL_ROOT=/redmine
      - TZ=Europe/Vienna
      - REDMINE_HTTPS=true
      - REDMINE_PORT=10083
      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15
      - REDMINE_CONCURRENT_UPLOADS=2
      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=mr-36dfR
      - DB_NAME=redmine_production

    ports:
      - '3001:80'
    volumes:
      - redmine-app-persistence:/home/redmine/data
    depends_on:
      - mariadb

volumes:
  redmine-db-persistence:
  redmine-app-persistence:
```

So I assume my problem relates to https vs. http in the apache-mod_proxy forwarding?

**Comment by jcormier** [comment]
My apache proxy setup looks like.

```
        <VirtualHost _default_:443>
...
                # REDMINE Pass connections to docker
                ProxyRequests Off
                ProxyPass /redmine http://127.0.0.1:10080/redmine/
                ProxyPassReverse /redmine http://127.0.0.1:10080/redmine/
```

And from my docker-compose.yml file:
```
  redmine:
    environment:
...
    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=/redmine
...
    ports:
# Bind to localhost, apache will proxy user to server
    - "127.0.0.1:10080:80"
```
