### ISSUE TITLE
Upgrade 3.4.7-3 -> 4.0.0 fail

### ISSUE THREAD

**Issue by prodigy7** [sameersbn/docker-redmine#382]
Today I try to upgrade from 3.4.7-3 to 4.0.0 but it fails during docker start:

```
redmine_1             | Configuring redmine::incoming_email...
redmine_1             | Configuring redmine::fetch_commits...
redmine_1             | ERROR: Unsupported Redmine version (4.0.0)
```

Some part in 3.4.7-3:

```
redmine_1             | Configuring redmine::incoming_email...
redmine_1             | Configuring redmine::fetch_commits...
redmine_1             | Configuring redmine::backups...
redmine_1             | Configuring redmine::backups::schedule...
redmine_1             | Configuring nginx...
redmine_1             | Configuring nginx::redmine...
redmine_1             | Installing plugins...
redmine_1             | Installing themes...
```

Something wrong with backup?

**Comment by jcormier** [comment]
Also, set DEBUG=true and post the whole start log.

**Comment by prodigy7** [comment]
Here the last lines of the debugging outpout before the error occourse and the messages repeat:

```
redmine_1             | + sed -ri 's/[{]{2}SMTP_OPENSSL_VERIFY_MODE[}]{2}/${SMTP_OPENSSL_VERIFY_MODE}/g' /tmp/tmp.TTYuNJGaQN
redmine_1             | + for variable in '${VARIABLES[@]}'
redmine_1             | + sed -ri 's/[{]{2}SMTP_STARTTLS[}]{2}/${SMTP_STARTTLS}/g' /tmp/tmp.TTYuNJGaQN
redmine_1             | + for variable in '${VARIABLES[@]}'
redmine_1             | + sed -ri 's/[{]{2}SMTP_TLS[}]{2}/${SMTP_TLS}/g' /tmp/tmp.TTYuNJGaQN
redmine_1             | + export SMTP_METHOD SMTP_HOST SMTP_PORT SMTP_DOMAIN SMTP_USER SMTP_PASS SMTP_AUTHENTICATION SMTP_OPENSSL_VERIFY_MODE SMTP_STARTTLS SMTP_TLS
redmine_1             | + local IFS=:
redmine_1             | + sudo -HEu redmine envsubst '$SMTP_METHOD:$SMTP_HOST:$SMTP_PORT:$SMTP_DOMAIN:$SMTP_USER:$SMTP_PASS:$SMTP_AUTHENTICATION:$SMTP_OPENSSL_VERIFY_MODE:$SMTP_STARTTLS:$SMTP_TLS'
redmine_1             | + rm -f /tmp/tmp.TTYuNJGaQN
redmine_1             | + [[ false == true ]]
redmine_1             | + exec_as_redmine sed -i -e '/{{SMTP_CA_PATH}}/d' -e '/{{SMTP_CA_FILE}}/d' /home/redmine/redmine/config/configuration.yml
redmine_1             | ++ whoami
redmine_1             | + [[ root == redmine ]]
redmine_1             | + sudo -HEu redmine sed -i -e '/{{SMTP_CA_PATH}}/d' -e '/{{SMTP_CA_FILE}}/d' /home/redmine/redmine/config/configuration.yml
redmine_1             | + redmine_configure_incoming_email
redmine_1             | + [[ true == true ]]
redmine_1             | + echo 'Configuring redmine::incoming_email...'
redmine_1             | Configuring redmine::incoming_email...
redmine_1             | + crontab -u redmine -l
redmine_1             | + grep -q redmine:email:receive_imap /tmp/cron.redmine
redmine_1             | + crontab -u redmine /tmp/cron.redmine
redmine_1             | + rm -rf /tmp/cron.redmine
redmine_1             | + redmine_configure_fetch_commits
redmine_1             | + case ${REDMINE_FETCH_COMMITS} in
redmine_1             | + crontab -u redmine -l
redmine_1             | + grep -q Repository.fetch_changesets /tmp/cron.redmine
redmine_1             | + echo 'Configuring redmine::fetch_commits...'
redmine_1             | + case ${REDMINE_VERSION} in
redmine_1             | Configuring redmine::fetch_commits...
redmine_1             | + echo 'ERROR: Unsupported Redmine version (4.0.0)'
redmine_1             | + return 1
redmine_1             | ERROR: Unsupported Redmine version (4.0.0)
```

My docker-compose.yml (anonymized):

```
version: "2"

services:
  redmine:
    image: sameersbn/redmine:3.4.7-3
    restart: always
    depends_on:
      - redmine-mysql
      - redmine-memcached
    networks:
      - redmine-network
    ports:
      - "10080:80"
    links:
      - redmine-mysql:mysql
      - redmine-memcached:memcached
    environment:
      - REDMINE_PORT=10083
      - REDMINE_BACKUP_SCHEDULE=daily
      - REDMINE_SECRET_TOKEN=randomSecretHere
      - REDMINE_BACKUP_EXPIRY=604800
      - REDMINE_FETCH_COMMITS=hourly
      - SMTP_HOST=mymailserver.com
      - SMTP_ENABLED=true
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_PORT=25
      - SMTP_DOMAIN=redmine.mydomain.com
      - DB_ADAPTER=mysql2
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=redmine_production
      - DB_USER=redmine
      - DB_PASS=mysqlSecret
      - IMAP_ENABLED=true
      - IMAP_USER=user@mymailserver.com
      - IMAP_PASS=myMailSecret
      - IMAP_HOST=imap.mymailserver.com
      - IMAP_PORT=993
      - IMAP_SSL=true
      - IMAP_INTERVAL=1
      - IMAP_MOVE_ON_SUCCESS=INBOX/Processed
      - IMAP_MOVE_ON_FAILURE=INBOX/Ignored
      - INCOMING_EMAIL_UNKNOWN_USER=accept
      - INCOMING_EMAIL_NO_PERMISSION_CHECK=true
      - INCOMING_EMAIL_NO_ACCOUNT_NOTICE=true
      - INCOMING_EMAIL_PROJECT=without-assignment
      - INCOMING_EMAIL_TRACKER=Unknown
      - INCOMING_EMAIL_ALLOW_OVERRIDE=project,tracker
      - NGINX_MAX_UPLOAD_SIZE=512m
      - MEMCACHE_HOST=redmine-memcached
      - MEMCACHE_PORT=11211
    volumes:
      - /opt/docker/redmine/core:/home/redmine/data
      - /opt/docker/git/download:/home/redmine/download
      - /opt/docker/git/core:/home/redmine/git
      - /opt/docker/redmine/log:/home/redmine/redmine/log

  redmine-memcached:
    image: sameersbn/memcached:1.5.6-1
    networks:
      - redmine-network
    restart: always

  redmine-mysql:
    image: sameersbn/mysql:5.7.24
    restart: always
    networks:
      - redmine-network
    ports:
      - "13306:3306"
    environment:
      - DB_NAME=redmine_production
      - DB_USER=redmine
      - DB_PASS=mysqlSecret
    volumes:
      - /opt/docker/redmine/mysql:/var/lib/mysql

networks:
  redmine-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16
```
