### ISSUE TITLE
Can't connect to image, connection refused

### ISSUE THREAD

**Issue by mgscreativa** [sameersbn/docker-redmine#389]
Hi! I'm trying to get started with this docker-compose.yml file
```
version: '2'

services:
  web:
    image: sameersbn/redmine:latest
    restart: always
    hostname: 'redmine.mgscreativa.com.ar'
    container_name: redmine
    environment:
    - TZ=America/Argentina/Buenos_Aires

    - DB_ADAPTER=mysql2
    - DB_HOST=10.0.0.77
    - DB_PORT=3306
    - DB_USER=XXXXXX
    - DB_PASS=XXXXXX
    - DB_NAME=XXXXXX

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - NGINX_HSTS_MAXAGE=2592000

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - SMTP_ENABLED=false
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "10083:3080"
    - "10445:3443"
    volumes:
    - /media/data/redmine/files:/home/redmine/data
```

After successful docker-compose up -d I can't connect to the docker app. From host machine I'm trying to access http://10.0.0.77:3080 and nothing happens. Tryed  `netcat -z -v 10.0.0.77 3080` but got `netcat: connect to 10.0.0.77 port 3080 (tcp) failed: Connection refused`

Also got into container with `sudo docker exec -i -t redmine /bin/bash` and can connect to mysql remote server at 10.0.0.77 from there, and can ping 10.0.0.77 from container.

Any ideas?

Thanks!

PS: No obvious log messages found

**Comment by jcormier** [comment]
Not really sure what your trying to do with your port forwards.

```
    ports:
    - "10083:3080"
    - "10445:3443"
```

The port forwards are, I think backwards to what you expected.  It goes <external>:<internal>.

So I assume you wanted something like
```
    ports:
    - "3080:80"
    - "3443:443"
```

**Comment by mgscreativa** [comment]
Hi @jcormier ! Thanks for the answer

I have changed ports in my docker-compose.yml file like this, set REDMINE_PORT=80 and ports: "3080:80" and "3443:443"
```
version: '2'

services:
  web:
    image: sameersbn/redmine:latest
    restart: always
    hostname: 'redmine.mgscreativa.com.ar'
    container_name: redmine
    environment:
    - TZ=America/Argentina/Buenos_Aires

    - DB_ADAPTER=mysql2
    - DB_HOST=10.0.0.77
    - DB_PORT=3306
    - DB_USER=XXXXXX
    - DB_PASS=XXXXXX
    - DB_NAME=XXXXXX

    - REDMINE_PORT=80
    - REDMINE_HTTPS=true
    - NGINX_HSTS_MAXAGE=2592000

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - SMTP_ENABLED=false
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "3080:80"
    - "3443:443"
    volumes:
    - /media/data/redmine/files:/home/redmine/data

```
Still can't connect `netcat -z -v 10.0.0.77 3080` gets `netcat: connect to 10.0.0.77 port 3080 (tcp) failed: Connection refused`

**# composer ps: (seems right)**

> 041eaf7f2e8e        sameersbn/redmine:latest   "/sbin/entrypoint.sh…"   11 seconds ago      Up 10 seconds       0.0.0.0:3080->80/tcp, 0.0.0.0:3443->443/tcp                       redmine
