### ISSUE TITLE
Unable to uninstall plugin

### ISSUE THREAD

**Issue by Sir-Will** [sameersbn/docker-redmine#400]
I'm trying to uninstall the plugin Global Roles but wasn't able to so far.

I added the line `command: app:rake redmine:plugins:migrate NAME=global_roles VERSION=0 RAILS_ENV=production` to the docker-composer.yml and restarted the container which resulted in the error that the plugin `global_roles` wasn't found.

I also tried running `docker exec -it redmine sudo -u redmine -H bundle exec rake redmine:plugins:migrate NAME=global_roles VERSION=0 RAILS_ENV=production` which did revert the database changes but after removing the plugin from the plugins directory and restarting it added all the database changes again.

**Comment by Sir-Will** [comment]
Just tried the docker-compose and it throws the "No such service" error although the container with that name is running.

**Comment by jcormier** [comment]
> Just tried the docker-compose and it throws the "No such service" error although the container with that name is running.

Please include logs of the commands you are running.  And a redacted version of your docker-compose.yml

**Comment by Sir-Will** [comment]
```
root@webUtil ~/docker/redmine # docker-compose exec redmine bundle exec rake redmine:plugins:migrate NAME=global_roles VERSION=0
ERROR: No such service: redmine

CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                                            NAMES
09c39c2ace60        sameersbn/redmine:3.4.10-1          "/sbin/entrypoint.sh…"   13 hours ago        Up 13 hours         <redacted>:80->80/tcp, 443/tcp                              redmine
```
/root/docker/redmine/docker-compose.yml:
```
postgresql:
  image: sameersbn/postgresql:latest
  environment:
    - TZ=Europe/Berlin
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
  volumes:
    - /srv/docker/redmine/redmine/postgresql:/var/lib/postgresql
redmine:
  image: sameersbn/redmine:3.4.10-1
  links:
    - postgresql:postgresql
    - memcached:memcached
  environment:
    - TZ=Europe/Berlin
    - REDMINE_PORT=80
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=<redacted>
    - SMTP_HOST=<redacted>
    - SMTP_PORT=<redacted>
    - SMTP_USER=<redacted>
    - SMTP_PASS=<redacted>
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login
  ports:
    - "<redacted>"
  volumes:
    - /srv/docker/redmine/redmine/redmine:/home/redmine/data
memcached:
  image: sameersbn/memcached:latest
```
