### ISSUE TITLE
chmod: cannot access '/home/redmine/data': No such file or directory

### ISSUE THREAD

**Issue by shahid28** [sameersbn/docker-redmine#423]
Hi,
I am running the Redmine version 4.0.3(sameersbn/redmine:4.0.3) or 4.0.7(sameersbn/redmine:4.0.7) using docker on Ubuntu 18, getting the following error

```
Attaching to redmine_redmine_1
redmine_1  | Initializing logdir...
redmine_1  | Initializing datadir...
redmine_1  | chmod: cannot access '/home/redmine/data': No such file or directory
redmine_redmine_1 exited with code 1
```
My docker-compose file 

```
services:
  redmine:
    image: sameersbn/redmine:4.0.3
    ports:
      - 8094:80
    volumes:
      - ./redmine-plugins:/usr/src/redmine/plugins
      - ./redmine-themes:/usr/src/redmine/public/themes
      - ./redmine-files:/usr/src/redmine/files
   
    environment:
      REDMINE_SECRET_KEY_BASE: "test"
      REDMINE_DB_POSTGRES: 192.168.110.135
      REDMINE_DB_PASSWORD: test
      REDMINE_DB_PORT: 5432
      REDMINE_DB_USERNAME: test
      REDMINE_DB_DATABASE: redmine
```

I am missing thing there
