### ISSUE TITLE
Redmine cant recognize domain/hostname but I can send emails from command line

### ISSUE THREAD

**Issue by Avskum** [sameersbn/docker-redmine#433]
I am using helpdesk plugin, so I can reply on tickets and send them back to the customer via redmine.

But I just ran into problem, which I can't solve for few days. I have postfix relay server on external server which works for most of my projects `smtpinternal.domain.tld`

I have this in my redmine config like this

```
# default configuration options for all environments
default: 
  # Outgoing emails configuration
  # See the examples below and the Rails guide for more configuration options:
  # http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: false
      address: 'smtp.smtpinternal.domain.tld'
      port: 25
      domain: 'smtpinternal.domain.tld'
      tls: false
```

Sadly, when I want in my redmine instance try to send test email I have this error message

`getaddrinfo: Name or service not known`

weird thing is that, I wanted to send test email with mail utility in the container, to test if I can resolve `hostnames`, and it worked. I can even ping on my `Nameservers` .. any idea, why redmine refuse to send emails?
