### ISSUE TITLE
Question：How to use with MariaDB, or other image composed with MariaDB?

### ISSUE THREAD

**Issue by asyahana** [sameersbn/docker-redmine#471]
Thank you for your help.
I'm thinking of using your Docker image in a Redmine update, but my boss told me to use MariaDB for the database (because my boss is an anti-oracle ...).
Therefore, I would like to use MariaDB in consideration of portability, but I have tried several things, but it does not work very well.
Sorry to trouble you, but could you please tell me how to build using MariaDB or a Docker image created using it?

**Comment by jcormier** [comment]
I've never tried to use MariahDB but a few people have posted examples.  You could try this docker-compose. https://github.com/sameersbn/docker-redmine/issues/312#issue-260562284

**Comment by asyahana** [comment]
Thanks a lot!
But I tried to run docker-compose, but I got an error like the one in the image.
Not only database engine is MariaDB but also MySQL appears, which is a problem. 
I'm sorry often, Can you tell me if there is any workaround?
![image](https://user-images.githubusercontent.com/64050777/124701004-c6af5f80-df28-11eb-8c6d-2619e98c9810.png)

docker-compose.yml
```
version: '3.8'

services:
  database:
    image: kazaoki/mariadb-mroonga:latest
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      DB_USER: u_redmine
      DB_PASS: redmine
      DB_NAME: db_redmine
    volumes:
      - ./redmine/mysql:/var/lib/mysql
      
  redmine:
    image: sameersbn/redmine:4.2.1-1
    depends_on:
      - database
      - memcached
    environment:
      TZ: Asia/Tokyo

      DB_ADAPTER: mysql2
      DB_HOST: database
      DB_PORT: 3306
      
      DB_USER: u_redmine
      DB_PASS: redmine
      DB_NAME: db_redmine

      REDMINE_PORT: 3000
      REDMINE_HTTPS: 0
      REDMINE_RELATIVE_URL_ROOT: /redmine
      REDMINE_SECRET_TOKEN: 

      REDMINE_SUDO_MODE_ENABLED: 0
      REDMINE_SUDO_MODE_TIMEOUT: 15

      REDMINE_CONCURRENT_UPLOADS: 2

      REDMINE_BACKUP_SCHEDULE: daily
      REDMINE_BACKUP_EXPIRY: 
      REDMINE_BACKUP_TIME: 
      
      MEMCACHE_HOST: memcached
      MEMCACHE_PORT: 11211

      SMTP_ENABLED: 1
      SMTP_METHOD: smtp
      SMTP_DOMAIN: ics-p.jp
      SMTP_HOST: icsp-jp0i.mail.protection.outlook.com
      SMTP_PORT: 25
      SMTP_USER: 
      SMTP_PASS: 
      SMTP_STARTTLS: 1
      SMTP_AUTHENTICATION: :none

    ports:
      - 3000:80
    volumes:
      - /srv/docker/redmine/redmine_mysql:/home/redmine/data
      - /srv/docker/redmine/redmine-logs:/var/log/redmine

  memcached:
    image: 'sameersbn/memcached:latest'
    container_name: memcached
    ports:
      - 11211:11211
    restart: always
```

**Comment by jcormier** [comment]
Your mariadb env arguments are incorrect. https://hub.docker.com/_/mariadb

```
  database:
    image: kazaoki/mariadb-mroonga:latest
    environment:
      TZ: Asia/Tokyo
      MARIADB_USER: u_redmine
      MARIADB_PASSWORD: redmine
      MARIADB_DATABASE: db_redmine
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - /srv/docker/redmine/mariadb:/var/lib/mysql
```
