### ISSUE TITLE
Unable to connect using SSL

### ISSUE THREAD

**Issue by boujrafh** [sameersbn/docker-redmine#489]
Hello @sameersbn ,

Great job you did.

Unfortunately, I was unable to use SSL.

I have an OVH domain and therefore I created my own certificates.

==> fullchain.pem which I renamed .CRT
==> privkey.key which I renamed .key
==> and I generated dhparam.pem certificate

I used the example from your docker-compose-ssl.yml unfortunately I can only access url through port 10083 but not using 10445.

Could you help me understand my error please?

And the last question : how to add my domain on the docker-compose.yml file

```
version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-4
    environment:
    - DB_USER=redmine
    - DB_PASS=xxxxxxxxxxxxxxxxxx
    - DB_NAME=redmine_production
    volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql

  redmine:
    build: ./
    image: sameersbn/redmine:4.2.3-1
    depends_on:
    - postgresql
    environment:
    - TZ=Europe/Brussels

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmine
    - DB_PASS=xxxxxxxxxxxxx
    - DB_NAME=redmine_production
    - DB_SSL_MODE=prefer

    - REDMINE_PORT=10445
    - REDMINE_HTTPS=true
    # Defaults for ssl path.  Please read https://github.com/sameersbn/docker-redmine#ssl
    - SSL_KEY_PATH=/home/redmine/data/certs/services.xxxxxxxx.ovh.key
    - SSL_CERTIFICATE_PATH=/home/redmine/data/certs/services.xxxxxxxxxx.ovh.crt
    - SSL_DHPARAM_PATH=/home/redmine/data/certs/dhparam.pem
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=daily
    - REDMINE_BACKUP_EXPIRY=604800
    - REDMINE_BACKUP_TIME=04:00

    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=smtp.gmail.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=services.xxxxxxxxxxx@gmail.com
    - SMTP_PASS=eywgwbjprygyjsim
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=true
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=services.xxxxxxx@gmail.com
    - IMAP_PASS=xxxxxxxxxx
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "10083:80"
    - "10445:443"
    - "587:587"
    - "993:993"

    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
    - /srv/docker/redmine/certs:/home/redmine/data/certs
    - /srv/docker/redmine/redmine-logs:/var/log/redmine
    - /srv/docker/redmine/plugins:/home/redmine/data/plugins
    - /srv/docker/redmine/themes:/home/redmine/data/themes


```
