### ISSUE TITLE
ARM support for Docker image

### ISSUE THREAD

**Issue by ahanoff** [sameersbn/docker-redmine#510]
hi @sameersbn, 

may I check if it's possible to add support for ARM platform? I'm tryint to run it on my Mac M1 and getting this error: 

`no matching manifest for linux/arm64/v8 in the manifest list entries`

Below is docker-compose.yml used:

```yml
version: '2'

networks:
  redmine-net:
    driver: bridge

services:
  db:
    image: mariadb:10.5.19
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: redmine
    networks:
      - redmine-net
  redmine:
    image: sameersbn/redmine:5.0.5
    restart: always
    ports:
      - 8080:8080
    networks:
      - redmine-net
    volumes:
      - .redmine:/home/redmine/data
    env_file:
      - redmine.config
```
