### ISSUE TITLE
How to upgrade from sameersbn/redmine: 4.1.1-8 to sameersbn/redmine: 5.1.1-1 ?

### ISSUE THREAD

**Issue by wangyu8460958** [sameersbn/docker-redmine#535]
I deployed redmine 4.1 using this docker-compose.yml file, part of docker-compose.yml is shown below:

```
version: '2'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    environment:
    - DB_USER=redmine
    - DB_PASS=redmine
    - DB_NAME=redmine
    volumes:
    - /mnt/data/redmine/postgresql:/var/lib/postgresql

  memcached:
    restart: always
    image: sameersbn/memcached:latest

  redmine:
    restart: always
    image: sameersbn/redmine:4.1.1-8
#    image: sameersbn/redmine:2.6.10-8
    depends_on:
    - postgresql
    - memcached
```

Then I want to update to redmine 5.1 , I use  this docker-compose.yml file:  https://github.com/sameersbn/docker-redmine/blob/master/docker-compose-memcached.yml

I exported postgresql 9 to a sql file and imported it to postgresql 14, and the import reported an error:

![9I_P2138}G$LLC)193HKR99](https://github.com/sameersbn/docker-redmine/assets/34674414/cbbf157c-543e-4adf-90b5-14ad63ecfecb)

My question is :
1.   I want to upgrade from sameersbn/redmine:4.1.1-8 to sameersbn/redmine:5.1.1-1, is it possible? If it can be achieved, what are the steps?
2.   Use https://github.com/sameersbn/docker-redmine/blob/master/docker-compose-memcached.yml to start redmine:5.1.1, the postgresql image can be changed to sameersbn/ postgresql:9.6-2 ?
3.   What is the default username and password for the redmine login screen after using https://github.com/sameersbn/docker-redmine/blob/master/docker-compose-memcached.yml to start redmine:5.1.1?
