### ISSUE TITLE
Can't download large files

### ISSUE THREAD

**Issue by marcosguedes** [sameersbn/docker-redmine#538]
Hi everyone, thanks a bunch for this project! I've been using Redmine with the provided docker-compose.yml for a few months now. I'm on 5.0.5 and it's all working fine, however, I noticed I can _upload_ large files by changing NGINX_MAX_UPLOAD_SIZE but I can't _download_ them. It fails midway.

My nginx reverse proxy gets the error `upstream prematurely closed connection while reading upstream` so I believe the error might come from nginx or unicorn timeouts inside the docker.

Here's my environment config (minus sensitive settings)

```
  postgresql:
    image: sameersbn/postgresql:9.6-4
    restart: unless-stopped
    container_name: redmine-postgresql
    ports:
      - "5484:5432"

  redmine:
    build: ./
    image: sameersbn/redmine:5.0.5
    restart: unless-stopped
    container_name: redmine
    depends_on:
      - postgresql
    ports:
      - "4000:80"

    volumes:
      - /srv/docker/redmine/redmine:/home/redmine/data
      - /srv/docker/redmine/redmine-logs:/var/log/redmine

    environment:
      - REDMINE_PORT=4000
      - REDMINE_HTTPS=true
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=


      - NGINX_MAX_UPLOAD_SIZE=4G
      - UNICORN_TIMEOUT = 600
```

I've changed all timeouts on my nginx reverse proxy to 600s so I don't think that's the cause.

nginx and unicorn logs on /srv/docker/redmine/redmine-logs/ don't provide any clues. Doing `docker logs redmine --follow` also doesn't show any errors. I don't know what else I should check to troubleshoot this

I'm _think_ the issue stems from nginx timeouts because I had similar problems on other projects with redmine installed manually. However, the logs don't show anything. Is there a way I can troubleshoot this better and/or change nginx timeouts if at all possible?

Thank you
