### ISSUE TITLE
Need to set RAILS_RELATIVE_URL_ROOT along with REDMINE_RELATIVE_URL_ROOT to make relative url work

### ISSUE THREAD

**Issue by thiru-mre** [sameersbn/docker-redmine#570]
Setting REDMINE_RELATIVE_URL_ROOT alone doesn't seem to be sufficient.  We need to set RAILS_RELATIVE_URL_ROOT with the same value. 

REDMINE_RELATIVE_URL_ROOT update nginx configuration while RAILS_RELATIVE_URL_ROOT takes care of Ruby on Rails Route.

```
    environment:
      NGINX_ENABLED: true
      REDMINE_RELATIVE_URL_ROOT: /it
      RAILS_RELATIVE_URL_ROOT: /it

```
